export const dom = {
  sceneRoot: document.querySelector("#scene-root"),
  locateMeButton: document.querySelector("#locate-me-button"),
  searchForm: document.querySelector("#location-search-form"),
  searchInput: document.querySelector("#location-search"),
  statusLine: document.querySelector("#status-line"),
  lastRefresh: document.querySelector("#last-refresh"),
  nextRefresh: document.querySelector("#next-refresh"),
  stationCount: document.querySelector("#station-count"),
  avgTemp: document.querySelector("#avg-temp"),
  selectionName: document.querySelector("#selection-name"),
  selectionCondition: document.querySelector("#selection-condition"),
  selectionTemperature: document.querySelector("#selection-temperature"),
  selectionWind: document.querySelector("#selection-wind"),
  selectionHumidity: document.querySelector("#selection-humidity"),
  selectionPressure: document.querySelector("#selection-pressure"),
  selectionCoordinates: document.querySelector("#selection-coordinates"),
  selectionDaylight: document.querySelector("#selection-daylight"),
  selectionProvider: document.querySelector("#selection-provider"),
  providerSelect: document.querySelector("#provider-select"),
  providerApiKey: document.querySelector("#provider-api-key"),
  providerSaveButton: document.querySelector("#provider-save-button"),
  providerKeyGroup: document.querySelector("#provider-key-group"),
  providerKeyNote: document.querySelector("#provider-key-note"),
  providerCapability: document.querySelector("#provider-capability"),
  quotaLimit: document.querySelector("#quota-limit"),
  quotaUsed: document.querySelector("#quota-used"),
  quotaRemaining: document.querySelector("#quota-remaining"),
  quotaNote: document.querySelector("#quota-note"),
  forecastList: document.querySelector("#forecast-list"),
  toggleMarkersButton: document.querySelector("#toggle-markers-button"),
  toggleTerminatorButton: document.querySelector("#toggle-terminator-button"),
  toggleHeatmapButton: document.querySelector("#toggle-heatmap-button"),
  togglePrecipitationButton: document.querySelector("#toggle-precipitation-button"),
  snackbar: document.querySelector("#snackbar"),
  sidebarToggle: document.querySelector("#sidebar-toggle"),
  rightSidebar: document.querySelector("#right-sidebar"),
  cloudSwitch: document.querySelector("#cloud-switch"),
  languageSelect: document.querySelector("#language-select"),
  toggleSettingsButton: document.querySelector("#toggle-settings-button"),
  settingsContent: document.querySelector("#settings-content"),
  selectionCloudCover: document.querySelector("#selection-cloud-cover"),
  selectionPrecipitation: document.querySelector("#selection-precipitation"),
  toggleWindButton:    document.querySelector("#toggle-wind-button"),
  toggleTiltSimpleButton: document.getElementById("toggle-tilt-simple-button"),
  toggleTiltSeasonalButton: document.getElementById("toggle-tilt-seasonal-button"),
  modeRealtimeBtn:     document.querySelector("#mode-realtime-btn"),
  modeForecastBtn:     document.querySelector("#mode-forecast-btn"),
  modelSelectorRow:    document.querySelector("#model-selector-row"),
  forecastTimeRow:     document.querySelector("#forecast-time-row"),
  forecastTimeSlider:  document.querySelector("#forecast-time-slider"),
  forecastTimeLabel:   document.querySelector("#forecast-time-label"),
};

// points and providerId are initialized in main.js after all modules are loaded
// to avoid circular dependencies (cache.js ↔ state.js)
export const weatherState = {
  points: [],
  showHeatmap: false,
  selectedPoint: null,
  averageMarkerScale: 1,
  lastUpdatedAt: null,
  nextRefreshAt: null,
  providerId: "openMeteo",
  providerQuotas: {},
  globalDataProvider: "Open-Meteo",
  selectionRequestToken: 0,
  showMarkers: true,
  showTerminator: true,
  cloudMode: "off",
  showPrecipitation: false,
  showWind: false,
  dataMode: "realtime",        // "realtime" | "forecast"
  forecastModel: "auto",       // "auto" | "gfs" | "icon" | "meteofrance" | "gem"
  forecastHours: 0,            // 0..72
  useRainViewer: false,        // true when RainViewer is actively rendering precipitation
  rightSidebarOpen: false,
  showSettings: true,
  globeTargetX: 1.6,
  tiltMode: "none",
  globeTargetTiltZ: 0,
  summaryStats: null,
  lastDistanceForScale: null,
  language: localStorage.getItem('terracast:language') ?? 'it'
};

export const interactionState = {
  isPointerDown: false,
  downX: 0,
  downY: 0,
  dragDistance: 0
};
